### ISSUE TITLE
Need ability to manage process mapping

### ISSUE THREAD

**Issue by ianfoster** [CODARcode/savanna#2]
We need the ability to manage the mapping of processes to nodes, so that we can e.g. partition a node and run a data-producing task concurrently with a staging service on the same nodes. That will allow for experimentation with the performance of different layouts.

My understanding is that this capability is not currently supported by Swift.

I have talked to a couple of people about this and my understanding is that I was told that MPI does not support this. However, Scott tells me that it IS supported at least on some machines. We need to clarify.

**Comment by mw70** [comment]
There is a complicated set of dependencies here.  On a machine like Cori, this is relatively easy -- the slurm scheduler allows you to launch multiple executables onto a single node, and with an extra couple of parameters you can tell the Cray hardware to map each of them onto a different "port" for the Aries network.  The Cray MPI will respect that, and you can co-run multiple applications on the same node -- I did a run where I loaded an analytics application onto each hyperthread, so simulation & analytics were technically on the same core.

That said, in conversations between Justin, Jong and me, we ran into some issues figuring out how to make that easy in swift/T.  There's a way to do a simple mapping on a Cori-like machine, but you have to set some external environment variables in order to make it work the way you want, and you can only do one analytics stage.  Enhancing that in swift/T was part of our goal for next year's release.  I have a solution with research code that would (partially) solve this even in difficult environments like Titan... but I don't know that that is the correct way forward.  We need a specific machine where we want to support this feature to drive our decisions.

**Comment by j-woz** [comment]
Do you have any thoughts about how to launch MPI applications like this?  I am in touch with Cray engineers but they don't seem to think it will work.

**Comment by mw70** [comment]
What way are you asking about?  The Cori/Cray example is documented on their website -- http://www.nersc.gov/users/computational-systems/cori/running-jobs/advanced-running-jobs-options/, at least in terms of how to set the craynetworks flag properly.

For something like titan, you have to cheat.  We built an MPI shim library.  You fork/exec the other jobs, and then reroute the MPI calls to whomever owns the network, since only one process can be connected w/the Seastar interconnect.  That's part of the project I have wanted to get you & Jai Dayal to talk about.  I think we might be able to integrate his solution into swift/T's runtime, but we'd have to have a deep dive on some of the pieces.

**Comment by ianfoster** [comment]
The immediate driver is the fusion co-design study that Scott and his colleagues are defining. 

Scott et al., what machines are you targeting, initially? Titan? Theta? Summit? Cori?

With Bryce’s new pure Python script for launching pipelines, perhaps we don’t need the support in Swift for the fusion app, is that right?

**Comment by j-woz** [comment]
The recent work in Swift for this is here: https://bitbucket.org/jmjwozniak/mpix_launch_swift/src/ccd7d31b4ca0/apps/multi-1/?at=placement

**Comment by kshitij-v-mehta** [comment]
Closing this, as this has been moved to Cheetah and is handled as the 'node layout' functionality in Cheetah.
